language: cpp

compiler:
    - clang
    - gcc

os:
    - linux
    - osx

branches:
    only:
        - master
        - devel

matrix:
    exclude:
        - compiler: clang
          os: linux

addons:
  apt:
    sources:
      - george-edison55-precise-backports # for cmake 3.2.3 / doxygen 1.8.3
    packages:
      - cmake
      - cmake-data
      - libboost-all-dev

before_install:
    - git submodule update --init --recursive
    - git fetch --tags
    - sleep 1
    - git checkout $TRAVIS_BRANCH
    - export PROJECTGITVERSION=`git describe --tags --always |sed 's/^v//'`
    - echo $PROJECTGITVERSION
    - echo $TRAVIS_OS_NAME
    - echo $TRAVIS_COMMIT
    - echo $TRAVIS_TAG
    - export TRAVIS_TAG=`git describe --tags --exact-match HEAD 2>/dev/null`
    - echo $TRAVIS_TAG

install:
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install libfftw3-dev; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install cmake; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install fftw; fi
    #- if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install cmake; fi
    - cmake --version

script:
    - mkdir build
    - cd build
    - cmake -DFFTSCARF_BUILD_TEST:BOOL=ON -DFFTSCARF_PLAN_PROTECTACCESS:BOOL=ON -DFFTSCARF_PRECISION_SINGLE:BOOL=ON -DFFTSCARF_PRECISION_DOUBLE:BOOL=ON -DFFTSCARF_PRECISION_DEFAULTSINGLE:BOOL=ON -DFFTSCARF_FFT_OOURA:BOOL=ON -DFFTSCARF_FFT_FFTREAL:BOOL=ON -DFFTSCARF_FFT_PFFFT:BOOL=ON -DFFTSCARF_FFT_FFTW3:BOOL=ON -DFFTSCARF_FFT_FFTS:BOOL=ON ..
    - make
    - ls -l

    - cd test
    - ctest -V
