#os: Windows Server 2012 R2
os: Visual Studio 2015

platform:
  #- x86
  - x64

configuration:
  - Release
  
branches:
  only:
    - master
    - devel

build_script:
  - md build
  - cd build
  - cmake -G "Visual Studio 14 2015 Win64" ..
  - cmake --build . --config Release
  - ctest
