os: Visual Studio 2015
#os: Windows Server 2012 R2

environment:
  BOOST_ROOT: C:\Libraries\boost_1_59_0

platform:
  - x86
  - x64

configuration:
  - Release
  
branches:
  only:
    - master
    - devel

install:
  - git fetch --tags 
  - git submodule update --init --recursive

  - echo APPVEYOR_REPO_TAG_NAME %APPVEYOR_REPO_TAG_NAME%
  - echo APPVEYOR_REPO_TAG %APPVEYOR_REPO_TAG%
  - echo appveyor_repo_tag_name %appveyor_repo_tag_name%
  - echo appveyor_repo_tag %appveyor_repo_tag%
  - ps: echo $env:platform

  # Set Boost lib dir
  - ps: if ($env:platform -eq 'x64') {$env:BOOST_LIBRARYDIR = "C:\Libraries\boost_1_59_0\lib64-msvc-14.0"}
  - ps: if ($env:platform -eq 'x86') {$env:BOOST_LIBRARYDIR = "C:\Libraries\boost_1_59_0\lib32-msvc-14.0"}

  # For the lib command
  - ps: cd "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC"
  #- ps: cd "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC"
  - cmd: if "%PLATFORM%" == "x64" call vcvarsall.bat amd64
  - cmd: if "%PLATFORM%" == "x86" call vcvarsall.bat x86
  - ps: cd "C:\projects\fftscarf"

  - ps: New-Item -ItemType directory -Name lib | Out-Null
  - ps: cd lib

  - ps: echo "Install FFTW3"
  #- ps: if ($env:platform -eq 'x64') {$libfft = "fftw-3.3.4-dll64"}
  #- ps: if ($env:platform -eq 'x86') {$libfft = "fftw-3.3.4-dll32"}
  - ps: if ($env:platform -eq 'x64') {$libfft = "fftw-3.3.5-dll64"}
  - ps: if ($env:platform -eq 'x86') {$libfft = "fftw-3.3.5-dll32"}
  - ps: echo $libfft
  - ps: New-Item -ItemType directory -Name $libfft | Out-Null
  - ps: cd $libfft
  - echo %CD%
  - ps: Invoke-WebRequest "ftp://ftp.fftw.org/pub/fftw/$libfft.zip" -OutFile "$libfft.zip"
  - ps: Get-ChildItem .
  - ps: 7z x "$libfft.zip" -y
  - ps: lib /machine:$env:platform /def:libfftw3-3.def
  - ps: lib /machine:$env:platform /def:libfftw3f-3.def
  - ps: lib /machine:$env:platform /def:libfftw3l-3.def
  - ps: cd ..
  - ps: Move-Item "$libfft" libfft
  - set PATH=C:\projects\fftscarf\lib\libfft;%PATH%
  - ps: Get-ChildItem C:\projects\fftscarf\lib\libfft

  # Leave lib folder
  - ps: cd ..

  - echo %CD%

  #- choco install cmake -version 3.2.3
  #- choco install make
  - ps: cmake --version


build_script:
  - md build
  - cd build
  - ps: echo $env:platform
  - ps: if ($env:platform -eq 'x64') {$env:GCONFIG="Visual Studio 14 2015 Win64"}
  - ps: if ($env:platform -eq 'x86') {$env:GCONFIG="Visual Studio 14 2015"}
  #- ps: if ($env:platform -eq 'x64') {$env:GCONFIG="Visual Studio 12 Win64"}
  #- ps: if ($env:platform -eq 'x86') {$env:GCONFIG="Visual Studio 12"}
  - cmake -G "%GCONFIG%" -DFFTSCARF_BUILD_TEST:BOOL=ON -DFFTSCARF_PLAN_PROTECTACCESS:BOOL=ON -DFFTSCARF_PRECISION_SINGLE:BOOL=ON -DFFTSCARF_PRECISION_DOUBLE:BOOL=ON -DFFTSCARF_PRECISION_DEFAULTSINGLE:BOOL=OFF -DFFTSCARF_FFT_OOURA:BOOL=ON -DFFTSCARF_FFT_FFTREAL:BOOL=ON -DFFTSCARF_FFT_FFTW3:BOOL=ON ..
  - ps: cmake --build . --config Release
  - ps: Get-ChildItem Release

  - echo Run tests
  - cmake --build . --config Release --target test_run
  - ps: cd test
  - ctest
