#os: Windows Server 2012 R2
os: Visual Studio 2015

environment:
  BOOST_ROOT: C:\Libraries\boost_1_59_0
  BOOST_LIBRARYDIR: C:\Libraries\boost_1_59_0\lib64-msvc-14.0

platform:
  #- x86
  - x64

configuration:
  - Release
  
branches:
  only:
    - master
    - devel

install:
  - git fetch --tags
  - echo APPVEYOR_REPO_TAG_NAME %APPVEYOR_REPO_TAG_NAME%
  - echo APPVEYOR_REPO_TAG %APPVEYOR_REPO_TAG%
  - echo appveyor_repo_tag_name %appveyor_repo_tag_name%
  - echo appveyor_repo_tag %appveyor_repo_tag%
  - ps: echo $env:platform

  #- ps: cd "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC"
##  - ps: Get-ChildItem .
  #- cmd: if "%PLATFORM%" == "x64" call vcvarsall.bat amd64
  #- cmd: if "%PLATFORM%" == "x86" call vcvarsall.bat x86
##  - cmd: vcvarsall amd64
  #- ps: cd "C:\projects\fftscarf"

  #- ps: New-Item -ItemType directory -Name lib | Out-Null
  #- ps: cd lib

  #- ps: echo "Install FFTW3"
  #- ps: if ($env:platform -eq 'x64') {$libfft = "fftw-3.3.4-dll64"}
  #- ps: if ($env:platform -eq 'x86') {$libfft = "fftw-3.3.4-dll32"}
  #- ps: echo $libfft
  #- ps: New-Item -ItemType directory -Name $libfft | Out-Null
  #- ps: cd $libfft
##  - echo %CD%
  #- ps: Invoke-WebRequest "ftp://ftp.fftw.org/pub/fftw/$libfft.zip" -OutFile "$libfft.zip"
  #- ps: Get-ChildItem .
##  - appveyor DownloadFile "ftp://ftp.fftw.org/pub/fftw/$libfft.zip"
  #- ps: 7z x "$libfft.zip" -y
  #- ps: lib /machine:$env:platform /def:libfftw3-3.def
  #- ps: Get-ChildItem .
  #- ps: cd ..
  #- ps: Move-Item "$libfft" libfft
##  - ps: Get-ChildItem C:\projects\dfasma\lib\fftw-3.3.4-dll32
##  - ps: lib /MACHINE:X86 /def:libfftw3-3.def # Needed only for MSVC (lib is still unrecognized command)

# Leave lib folder
  #- ps: cd ..

  - echo %CD%

  - git submodule update --init --recursive
#  - ps: cd ..

  - ps: Get-ChildItem .

  #- choco install cmake -version 3.2.3
  #- choco install make
  - ps: cmake --version


build_script:
  - ps: Get-ChildItem C:\Libraries\boost_1_59_0\lib64-msvc-14.0\libboost_unit_test_framework-vc140-mt-1_59.lib
  - md build
  - cd build
  - cmake -G "Visual Studio 14 2015 Win64" -DFFTSCARF_BUILD_TEST:BOOL=ON -DFFTSCARF_PRECISION_SINGLE:BOOL=ON -DFFTSCARF_PRECISION_DOUBLE:BOOL=ON -DFFTSCARF_PRECISION_DEFAULTSINGLE:BOOL=ON -DFFTSCARF_FFT_FFTREAL:BOOL=ON -DFFTSCARF_FFT_PFFFT:BOOL=OFF -DFFTSCARF_FFT_FFTW3:BOOL=OFF -DFFTSCARF_FFT_FFTS:BOOL=OFF -DFFTSCARF_FFT_IPP:BOOL=OFF -DFFTSCARF_PRECISION_SINGLE:BOOL=ON ..
  - cmake --build . --config Release
  - ps: Get-ChildItem .
  - ps: Get-ChildItem Release

  - echo Run tests
  - cmake --build . --config Release --target test_run
  #- ctest
