os: Windows Server 2012 R2

platform:
  #- x86
  - x64

configuration:
  - Release
  
branches:
  only:
    - master
    - devel

install:
  - git fetch --tags
  - echo APPVEYOR_REPO_TAG_NAME %APPVEYOR_REPO_TAG_NAME%
  - echo APPVEYOR_REPO_TAG %APPVEYOR_REPO_TAG%
  - echo appveyor_repo_tag_name %appveyor_repo_tag_name%
  - echo appveyor_repo_tag %appveyor_repo_tag%
  - ps: echo $env:platform
  
  - ps: cd "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC"
#  - ps: Get-ChildItem .
  - cmd: if "%PLATFORM%" == "x64" call vcvarsall.bat amd64
  - cmd: if "%PLATFORM%" == "x86" call vcvarsall.bat x86
#  - cmd: vcvarsall amd64
  - ps: cd "C:\projects\fftscarf"

  - ps: New-Item -ItemType directory -Name lib | Out-Null
  - ps: cd lib

  #- ps: echo "Install FFTW3"
  #- ps: if ($env:platform -eq 'x64') {$libfft = "fftw-3.3.4-dll64"}
  #- ps: if ($env:platform -eq 'x86') {$libfft = "fftw-3.3.4-dll32"}
  #- ps: echo $libfft
  #- ps: New-Item -ItemType directory -Name $libfft | Out-Null
  #- ps: cd $libfft
##  - echo %CD%
  #- ps: Invoke-WebRequest "ftp://ftp.fftw.org/pub/fftw/$libfft.zip" -OutFile "$libfft.zip"
  #- ps: Get-ChildItem .
##  - appveyor DownloadFile "ftp://ftp.fftw.org/pub/fftw/$libfft.zip"
  #- ps: 7z x "$libfft.zip" -y
  #- ps: lib /machine:$env:platform /def:libfftw3-3.def
  #- ps: Get-ChildItem .
  #- ps: cd ..
  #- ps: Move-Item "$libfft" libfft
##  - ps: Get-ChildItem C:\projects\dfasma\lib\fftw-3.3.4-dll32
##  - ps: lib /MACHINE:X86 /def:libfftw3-3.def # Needed only for MSVC (lib is still unrecognized command)

# Leave lib folder
  - ps: cd ..
  
  - echo %CD%
  
  - git submodule update --init --recursive
#  - ps: cd ..

  - choco install cmake -version 3.0.2
# - choco install make
  - ps: New-Item -ItemType directory -Name build | Out-Null
  - ps: cd build
  #- ps: if ($env:platform -eq 'x86') {cmake -DSDIF_BUILD_STATIC:BOOL=ON -DEASDIF_BUILD_STATIC:BOOL=ON -DCMAKE_INSTALL_PREFIX:STRING=c:/projects/dfasma/external/sdif/easdif ../EASDIF_SDIF}
  - ps: if ($env:platform -eq 'x64') {cmake -G"Visual Studio 12 Win64" -DFFTSCARF_BUILD_TEST:BOOL=ON -DFFTSCARF_PRECISION_DEFAULTSINGLE:BOOL=OFF -DFFTSCARF_FFT_FFTREAL:BOOL=ON -DFFTSCARF_FFT_PFFFT:BOOL=ON -DFFTSCARF_FFT_FFTW3:BOOL=ON -DFFTSCARF_FFT_FFTS:BOOL=ON -DFFTSCARF_FFT_IPP:BOOL=ON -DFFTSCARF_PRECISION_SINGLE:BOOL=ON ..}
  - ps: Get-ChildItem .
  - ps: Get-ChildItem test

  # Go back to the project's root
  - ps: cd "c:\projects\fftscarf"

build_script:
# Compile
  #- C:\Qt\Tools\QtCreator\bin\jom.exe -f Makefile.Release
